version: "3"
services:
    dns:
      image: jpillora/dnsmasq
      ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8081:8080"
      env_file:
      - .env
    nginx:
      image: nginx
      ports:
      - "80:80"
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
    nginx.conf: {}
